---

api_host:     188.42.126.92:8006
api_user:     "root@pam"
api_password: ******
node:         "bidmachine-k8s-diff-apac04-old"
key_name: id_rsa.pub
clone_vm:     "VM4"

vms:
  master:
    name: "VM5"
    ipaddress: 192.168.1.30/24
    vmid: "105"
  slave:
    name: "VM6"
    ipaddress: 192.168.1.31/24
    vmid: "104"
