---

api_host:     188.42.126.92:8006
api_user:     "root@pam"
api_password: *****
node:         "bidmachine-k8s-diff-apac04-old"
key_name: ~/.ssh/authorized_keys
clone_vm:     "VM 9000"

vms:
  master:
    name: "VM10"
    ipaddress: 192.168.1.32/24
    gw: 192.168.1.254
    vmid: "110"
  slave:
    name: "VM11"
    ipaddress: 192.168.1.31/24
    gw: 192.168.1.254
    vmid: "111"
